spring.application.name=apartmentmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/apartment_manager
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

aws.region=us-east-1
aws.accessKey=xxxxxxxxxx
aws.secretKey=xxxxxxxxxx
aws.bucketName=apartment-documents


